### ISSUE TITLE
crash: large directory

### ISSUE THREAD

**Issue by robertfoss** [warner/magic-wormhole#138] opened 2017-01-31 00:25 UTC
When trying to send a large directory locally I run into this crash:

> Building zipfile..
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1331, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1185, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/wormhole/cli/cmd_send.py", line 58, in go
    d = self._go(w)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1331, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1185, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/wormhole/cli/cmd_send.py", line 70, in _go
    offer, self._fd_to_send = self._build_offer()
  File "/usr/local/lib/python2.7/dist-packages/wormhole/cli/cmd_send.py", line 235, in _build_offer
    num_files += 1
  File "/usr/lib/python2.7/zipfile.py", line 801, in __exit__
    self.close()
  File "/usr/lib/python2.7/zipfile.py", line 1347, in close
    " would require ZIP64 extensions")
zipfile.LargeZipFile: Central directory offset would require ZIP64 extensions
ERROR: Central directory offset would require ZIP64 extensions

**Comment by warner** [comment] 2017-01-31 23:01
oops. could you give us an idea of how large that directory was? (total number of files might be the significant metric.. not sure what exactly goes into a "Central directory offset").

I think fixing this will require one or more of:

* figuring out how to enable ZIP64 extensions, if even possible
* if some platforms can use those extensions and some cannot, then we want to use them only when strictly necessary
* finding out when they're necessary
* advising the remote end that they'll need the extensions early (before the bulk .zip transfer has happened, rather than afterwards)

**Comment by robertfoss** [comment] 2017-02-01 00:43
About 24GB I believe, ~1000 files.

On Jan 31, 2017 18:01, "Brian Warner" <notifications@github.com> wrote:

oops. could you give us an idea of how large that directory was? (total
number of files might be the significant metric.. not sure what exactly
goes into a "Central directory offset").

I think fixing this will require one or more of:

   - figuring out how to enable ZIP64 extensions, if even possible
   - if some platforms can use those extensions and some cannot, then we
   want to use them only when strictly necessary
   - finding out when they're necessary
   - advising the remote end that they'll need the extensions early (before
   the bulk .zip transfer has happened, rather than afterwards)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/warner/magic-wormhole/issues/138#issuecomment-276521705>,
or mute the thread

**Comment by warner** [comment] 2017-02-02 19:58
I checked the python `zipfile` docs, and turning on `allowZip64=True` looks safe:

* it only affects the sending side (ZipFile writer): the ZipFile reader always accepts Zip64-mode files, so we don't need to add anything to the Wormhole protocol to prepare the receiver for a mode switch
* it's implemented entirely in Python: so all platforms can use it
* according to the debian `zip` docs, Zip64 mode is needed when any individual file is larger than 4GB, the overall archive is larger than 4GB, or there are more than 64K files in the archive. It has slightly more overhead (larger headers, etc), so it's only used if necessary.

The only reason `zipfile` doesn't turn it on by default is because the unix `/usr/bin/zip` and `unzip` utilities didn't originally support Zip64 mode. But from what I can find in the various Changelog files, that was at least 10 years ago, and magic-wormhole doesn't use an external `unzip` program anyways, so we don't need to be compatible with one. Also, the `zipfile` module switched the `Zip64=` default to True starting in python3.4, so they must have come to the same conclusion.

I've got a patch that I'll land momentarily, which ought to fix this. Could you give it a test? I'll wait for your ack before closing this one.

**Comment by robertfoss** [comment] 2017-02-02 21:00
I seem to be running into another issue now:

 $ wormhole send .
Building zipfile..
Warning: errors may occur unless both sides are running the same version
Server claims 0.9.2 is current, but ours is 0.9.2+2.g20619bc.dirty
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1331, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1185, in _inlineCallbacks
    result = g.send(result)
  File "build/bdist.linux-x86_64/egg/wormhole/cli/cmd_send.py", line 58, in go
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1331, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1185, in _inlineCallbacks
    result = g.send(result)
  File "build/bdist.linux-x86_64/egg/wormhole/cli/cmd_send.py", line 70, in _go
    
  File "build/bdist.linux-x86_64/egg/wormhole/cli/cmd_send.py", line 237, in _build_offer
    
  File "/usr/lib/python2.7/zipfile.py", line 801, in __exit__
    self.close()
  File "/usr/lib/python2.7/zipfile.py", line 1327, in close
    self.fp.write(filename)
  File "/usr/lib/python2.7/tempfile.py", line 626, in write
    rv = file.write(s)
exceptions.MemoryError: out of memory
ERROR: out of memory

**Comment by warner** [comment] 2017-02-02 21:56
Ah, that turns this into a duplicate of #58 . `wormhole send` currently creates the entire zipfile in memory before sending it, so you can't currently send a directory that's larger than your total RAM (plus swap space).

(Also, I just noticed that the Zip64 problem was a dup of #63)

We should totally fix that, but it's not easy: see the comments on #58 for details.

I'll close this one, now that the initial Zip64 thing is no longer the immediate problem. Thanks!

**Closed by warner** 2017-02-02 21:56 UTC

**Comment by warner** [comment] 2017-02-02 22:02
Oh, incidentally, we aren't strictly building the zipfile in RAM. We're using tempfile.SpooledTemporaryFile, which uses RAM until the data gets too big, then moves it to a tempfile. If you're seeing a MemoryError, that implies that either the SpooledTemporaryFile is not correctly moving to disk when it should, or that your `/tmp` directory (or `$TMPDIR` or something) is on a ramdisk, so it can't overflow when it needs to. (do you see out-of-memory errors in your kernel logs? or if you watch the system with 'top', does it show the memory usage of `wormhole send` growing unreasonably?)

Now, the best solution is still to stream the directory out, as described in #58, because that wouldn't need a 24GB tempfile. But you might be able to make this work by changing `$TMPDIR` to point at a real disk, instead of a ramdisk.

Or, if you discover that SpooledTemporaryFile isn't doing the switchover thing correctly, maybe there's another bug lurking in here.
